version: 0.9.{build}

platform: x64
configuration: Release

before_build:
  - echo running cmake...
  - cmake -G "Visual Studio 12 Win64"

build:
  parallel: true
  project: TinyObjLoaderSolution.sln
